name: Ubuntu VPS

on: [workflow_dispatch]

jobs:
  ubuntu-vps:
    runs-on: ubuntu-latest

    steps:
      - name: ุฅุนุฏุงุฏ SSH ูุชุบููุฑ ุงูุจุงุณูุฑุฏ
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl unzip
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:Vbnb123@" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: ุชุญููู ngrok ูุชูุนููู
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          ./ngrok authtoken 2j6ue1gQRTP7TOaezrzUCLB94ud_58MZqcx2XfGTahkYvve9Q

      - name: ุจุฏุก ngrok TCP ุนูู ุจูุฑุช 22
        run: |
          ./ngrok tcp 22 > ngrok.log &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
          cat tunnels.json
          echo "-----------------------------------------"
          echo "๐ก ุงูุณุฎ ุงูุฑุงุจุท ุงูุชุงูู ููุฏุฎูู ุจู PuTTY ุฃู SSH:"
          echo
          cat tunnels.json | grep -o 'tcp://[0-9a-zA-Z\.\:]*'
          echo
          echo "๐งโ๐ป Username: root"
          echo "๐ Password: Vbnb123@"
          echo "๐ ุงูุชูุช ุงูุฌูุณุฉ. ุงููุฏุฉ ุงููุตูู: 6 ุณุงุนุงุช"
