name: Ubuntu VPS via LocalXpose (Fixed Path)

on: [workflow_dispatch]

jobs:
  ubuntu-vps:
    runs-on: ubuntu-latest

    steps:
      - name: โฌ ุฅุนุฏุงุฏ SSH ูุชูุนูู root
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl snapd
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:Vbnb123@" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: โก ุชูุตูุจ ูุชุดุบูู LocalXpose
        run: |
          sudo snap install localxpose
          /snap/bin/localxpose authtoken XydYfpFyTvSFr3bLbyObHkSG3f5IkbCHGQGQUqwY
          /snap/bin/localxpose tcp --region eu --to localhost:22 > lx.log 2>&1 &
          sleep 10

      - name: ๐ก ุงุณุชุฎุฑุงุฌ ุฑุงุจุท ุงูุงุชุตุงู
        run: |
          echo "โ ุงูุณุฎ ุงูุฃูุฑ ุงูุชุงูู ููุฏุฎูู ุนูู ุงูู VPS:"
          grep -o 'tcp://[a-zA-Z0-9\.-]*:[0-9]*' lx.log || (echo "โ ุงูุฑุงุจุท ูุด ููุฌูุฏ โ ุญุงูู ุชุดุบูู Workflow ุชุงูู" && exit 1)
          echo
          echo "๐งโ๐ป Username: root"
          echo "๐ Password: Vbnb123@"
          echo "๐ ุงูุฌูุณุฉ ุดุบุงูุฉ ููุฏุฉ 6 ุณุงุนุงุช ุฃู ูุญุฏ ูุง ุชููู ุงูู workflow"
