name: Ubuntu VPS via Serveo

on: [workflow_dispatch]

jobs:
  ubuntu-vps:
    runs-on: ubuntu-latest

    steps:
      - name: ุฅุนุฏุงุฏ SSH ูุชุบููุฑ ุงูุจุงุณูุฑุฏ
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:Vbnb123@" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: ูุชุญ ุจูุฑุช 22 ุจุงุณุชุฎุฏุงู Serveo.net
        run: |
          ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 serveo.net > serveo.log 2>&1 &
          sleep 10
          echo "โ ุงูุณุฎ ุงูุฃูุฑ ุงูุชุงูู ููุฏุฎูู ุนูู ุงูู VPS:"
          grep -o 'ssh .*@.*serveo.net' serveo.log || echo "โ ูุดู ุงุณุชุฎุฑุงุฌ ุฑุงุจุท ุงูุงุชุตุงู"
          echo
          echo "๐งโ๐ป Username: root"
          echo "๐ Password: Vbnb123@"
          echo "๐ ุงูุฌูุณุฉ ุดุบุงูุฉ ููุฏุฉ 6 ุณุงุนุงุช ุฃู ูุญุฏ ูุง ุชููู ุงูู workflow"
