name: Ubuntu VPS via LocalXpose

on: [workflow_dispatch]

jobs:
  ubuntu-vps:
    runs-on: ubuntu-latest

    steps:
      - name: โฌ ุฅุนุฏุงุฏ SSH ูุชูุนูู ุงูุฏุฎูู root
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl unzip
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:Vbnb123@" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: โก ุชุญููู ูุชุดุบูู LocalXpose
        run: |
          wget https://localxpose.io/releases/localxpose-linux-amd64.zip -O lx.zip
          unzip lx.zip
          chmod +x localxpose
          ./localxpose authtoken XydYfpFyTvSFr3bLbyObHkSG3f5IkbCHGQGQUqwY
          ./localxpose tcp 22 > lx.log 2>&1 &

      - name: ๐ก ุงุณุชุฎุฑุงุฌ ุฑุงุจุท ุงูุงุชุตุงู
        run: |
          sleep 10
          echo "โ ุงูุณุฎ ุงูุฃูุฑ ุงูุชุงูู ููุฏุฎูู ุนูู ุงูู VPS:"
          tunnel=$(grep -o 'tcp://[a-zA-Z0-9\.:-]*' lx.log)
          if [ -z "$tunnel" ]; then
            echo "โ ูุดู ูู ุงุณุชุฎุฑุงุฌ ุงูุฑุงุจุท. ุฌุฑุจ ุชุดุบู ุงูู workflow ุชุงูู."
            exit 1
          fi
          echo
          echo "ssh root@${tunnel#tcp://}"
          echo
          echo "๐งโ๐ป Username: root"
          echo "๐ Password: Vbnb123@"
          echo "๐ ุงูุฌูุณุฉ ุดุบุงูุฉ ููุฏุฉ 6 ุณุงุนุงุช ุฃู ูุญุฏ ูุง ุชููู ุงูู workflow"
